Pass in identifiers as parametrs
Due to https://github.com/babel/babel/commit/a35e5a314ab533828d0988a2da824edb04fc8d3c, this plugin errors when a file contains a function type annotation:

```
TypeError: Property parameters expected type of array but got null
    at validate (/Users/ayao/code/discord/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at Object.validate (/Users/ayao/code/discord/node_modules/@babel/types/lib/definitions/utils.js:172:7)
    at validate (/Users/ayao/code/discord/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/Users/ayao/code/discord/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.TSFunctionType (/Users/ayao/code/discord/node_modules/@babel/types/lib/builders/generated/index.js:975:31)
    at convertFlowType (/Users/ayao/code/discord/node_modules/babel-plugin-flow-to-typescript/dist/converters/convert_flow_type.js:259:26)
    at Object.convertFlowType (/Users/ayao/code/discord/node_modules/babel-plugin-flow-to-typescript/dist/converters/convert_flow_type.js:184:38)
    at Object.convertTypeAlias (/Users/ayao/code/discord/node_modules/babel-plugin-flow-to-typescript/dist/converters/convert_type_annotation.js:15:37)
    at PluginPass.TypeAlias (/Users/ayao/code/discord/node_modules/babel-plugin-flow-to-typescript/dist/visitors/type_annotation.js:10:48)
    at newFn (/Users/ayao/code/discord/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:193:21)```

This update passes in the newly-added `parameters`.